# Pipeline for Gatter repository
#
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: windows-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'

- bash: |
    curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
    export PATH=$PATH:$HOME/.poetry/bin
    cd backend
    poetry install --no-root
  displayName: 'Install dependencies'

- bash: echo "##vso[task.prependpath]$HOME/.poetry/bin"
  displayName: Add poetry to PATH

- script: |
    cd backend
    poetry install
    poetry run black --check .
    poetry run isort --check-only .
  displayName: 'Check formatting'

- script: |
    cd backend
    poetry install
    poetry run flake8 .
    poetry run mypy .
  displayName: 'Check linting'

- script: |
    cd backend
    poetry install
    poetry run coverage erase
    poetry run coverage run -m pytest
    poetry run coverage report
  displayName: 'Tests and coverage'
